const mockBudgetData = [
  {
    user_id: 1,
    income_t_count: 2,
    expense_t_count: 4,
    balance: 778600,
    total_income: 880000,
    total_expenses: 101400,
    categorySpends: {
      January: [],
      February: [],
      March: [
        {
          categoryId: 7,
          amount: 300,
          mainCategoryName: "Social Life",
          icon: "🍺",
          year: 2023,
          month: "March",
        },
        {
          categoryId: 12,
          amount: 7500,
          mainCategoryName: "Self-Development",
          icon: "📱",
          year: 2023,
          month: "March",
        },
        {
          categoryId: 22,
          amount: 5000,
          mainCategoryName: "Clothing",
          icon: "👕",
          year: 2023,
          month: "March",
        },
        {
          categoryId: 21,
          amount: 10000,
          mainCategoryName: "Holiday",
          icon: "🏊‍♂️",
          year: 2023,
          month: "March",
        },
        {
          categoryId: 10,
          amount: 45600,
          mainCategoryName: "Self-Development",
          icon: "📚",
          year: 2023,
          month: "March",
        },
        {
          categoryId: 7,
          amount: 3000,
          mainCategoryName: "Social Life",
          icon: "🍺",
          year: 2023,
          month: "March",
        },
        {
          categoryId: 14,
          amount: 30000,
          mainCategoryName: "Transportation",
          icon: "🚆",
          year: 2023,
          month: "March",
        },
      ],
      April: [],
      May: [],
      June: [],
      July: [],
      August: [],
      September: [],
      October: [],
      November: [],
      December: [],
    },
    categoryIncome: {
      January: [],
      February: [],
      March: [
        {
          categoryId: 1,
          amount: 200000,
          mainCategoryName: "Salary",
          icon: "💰",
          year: 2023,
          month: "March",
        },
        {
          categoryId: 28,
          amount: 400000,
          mainCategoryName: "Bonus",
          icon: "💼",
          year: 2023,
          month: "March",
        },
        {
          categoryId: 2,
          amount: 30000,
          mainCategoryName: "Investments",
          icon: "💹",
          year: 2023,
          month: "March",
        },
        {
          categoryId: 3,
          amount: 250000,
          mainCategoryName: "Freelance Work",
          icon: "💼",
          year: 2023,
          month: "March",
        },
      ],
      April: [],
      May: [],
      June: [],
      July: [],
      August: [],
      September: [],
      October: [],
      November: [],
      December: [],
    },
  },
];

module.exports = mockBudgetData;
